In [7]:
import numpy as np
import torch
import matplotlib.pyplot as plt
torch.cuda.get_device_name(torch.cuda.current_device())

'GeForce RTX 3080'

In [2]:
# matrix element wise mul

m1 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

m2 = torch.tensor([
    [2,3,4],
    [5,6,7],
    [8,9,1]
])

torch.mul(m1, m2)

tensor([[ 2,  6, 12],
        [20, 30, 42],
        [56, 72,  9]])

In [14]:
torch.mul(m1, torch.tensor([0,1,2]))

tensor([[ 0,  2,  6],
        [ 0,  5, 12],
        [ 0,  8, 18]])

In [6]:
torch.sum(torch.mul(m1, m2), axis=0)

tensor([ 78, 108,  63])

In [11]:
# use something more than once in a computational graph
theta = torch.tensor(1, dtype=torch.float32, requires_grad=True)
x = torch.tensor(1, dtype=torch.float32, requires_grad=True)
b = torch.tensor(1, dtype=torch.float32, requires_grad=True)

((theta*x+b)/(theta**2)).backward()
theta.grad

tensor(-3.)

In [13]:
with None:
    print(12)

AttributeError: __enter__